name: Build esp32-xmpp-iot
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        sudo apt-get -y install gawk gperf grep gettext python python-dev automake bison flex texinfo help2man libtool libtool-bin make
    - name: Clone source code
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git
    - name: Generate config file
      run: |
        cd ~/esp/esp-idf
        ./install.sh all
    - name: make esp32-xmpp-iot
      run: |
        . $HOME/esp/esp-idf/export.sh
        git clone https://github.com/COM8/esp32-xmpp-iot.git
        cd esp32-xmpp-iot/ESP32
        bash init.sh
        idf.py build
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ESP32
        path: /home/runner/esp/esp-idf/esp32-xmpp-iot/ESP32/build
